// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-HBjCKRWnq-xF0R7OYKXthjDRjSOLl6g',
    appId: '1:195331976:web:b02ffb7fcc071d40c75c3d',
    messagingSenderId: '195331976',
    projectId: 'social-app-2ae1c',
    authDomain: 'social-app-2ae1c.firebaseapp.com',
    storageBucket: 'social-app-2ae1c.firebasestorage.app',
    measurementId: 'G-V234WPNW65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW2WireH4FB4LLg012Seb4XSv1qZc5bhE',
    appId: '1:195331976:android:fd1eb0d09a0c20ddc75c3d',
    messagingSenderId: '195331976',
    projectId: 'social-app-2ae1c',
    storageBucket: 'social-app-2ae1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcj_5E7kq241HqLS_0tm5KfAM2cf6E0eo',
    appId: '1:195331976:ios:fdb1c7c4ea224dfec75c3d',
    messagingSenderId: '195331976',
    projectId: 'social-app-2ae1c',
    storageBucket: 'social-app-2ae1c.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcj_5E7kq241HqLS_0tm5KfAM2cf6E0eo',
    appId: '1:195331976:ios:fdb1c7c4ea224dfec75c3d',
    messagingSenderId: '195331976',
    projectId: 'social-app-2ae1c',
    storageBucket: 'social-app-2ae1c.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-HBjCKRWnq-xF0R7OYKXthjDRjSOLl6g',
    appId: '1:195331976:web:6cf61e61f35047ddc75c3d',
    messagingSenderId: '195331976',
    projectId: 'social-app-2ae1c',
    authDomain: 'social-app-2ae1c.firebaseapp.com',
    storageBucket: 'social-app-2ae1c.firebasestorage.app',
    measurementId: 'G-KGM5T1CKFZ',
  );
}
